<?php
/* class app for e-Day admin
 * started at august 27th 2018
 * renamed at november 11th 2019
 * continue at november 28th 2019 -- version 1.1.0 -- being library namespace eday\kitchen
 */
namespace eday\kitchen;
use eday\admin;
use eday\site;
class app{
  const version='1.1.0';
  public function repair($ns=null){
    global $title,$files,$error,$namespace;
    $namespace=$ns;
    $files=self::files($ns);
    $error=$files?false:'Failed to get application files.';
    if(EDAY_ADMIN_TYPE!=='master'&&EDAY_ADMIN_TYPE!=='admin'){
      $error='Have no access to this page.';
    }
    $title='Application Reparation';
    admin::html('header');
    admin::html('menu');
    admin::html('app-repair');
    admin::html('footer');
    return true;
  }
  public function config($ns=null){
    global $title,$config,$error,$namespace;
    $config=self::configData($ns);
    $namespace=$ns;
    $error=$config?false:'Failed to get application config.';
    if(EDAY_ADMIN_TYPE!=='master'&&EDAY_ADMIN_TYPE!=='admin'){
      $error='Have no access to this page.';
    }
    $title='Application Configuration';
    admin::html('header');
    admin::html('menu');
    admin::html('app-config');
    admin::html('footer');
    return true;
  }
  public function all(){
    global $title,$apps,$error;
    $apps=unserialize(EDAY_APPS);
    $error=false;
    if(EDAY_ADMIN_TYPE!=='master'&&EDAY_ADMIN_TYPE!=='admin'){
      $error='Have no access to this page.';
    }
    $title='Application';
    admin::html('header');
    admin::html('menu');
    admin::html('app-all');
    admin::html('footer');
    return true;
  }
  public function ajax(){
    if(EDAY_ADMIN_TYPE!=='master'&&EDAY_ADMIN_TYPE!=='admin'){
      return self::error('Have no access to this page.');
    }
    $valid=['activateApp','saveAppConfig','fileContent','saveFile'];
    if(!isset($_POST['request'])
      ||!in_array($_POST['request'],$valid)
      ||!method_exists($this,$_POST['request'])){
      return self::error('Invalid request.');
    }return @\call_user_func_array([__CLASS__,$_POST['request']],[]);
  }
  private static function saveFile(){
    if(!isset($_POST['namespace'],$_POST['file'],$_POST['content'])
      ||!preg_match('/^[a-z0-9]+$/',$_POST['namespace'])
      ||preg_match('/^\./',$_POST['file'])){
      return self::error('Invalid data request.');
    }$apps=unserialize(EDAY_APPS);
    if(!array_key_exists($_POST['namespace'],$apps)){
      return self::error('Application is not available.');
    }$path=EDAY_APP_DIR.$_POST['namespace'].'/'.$_POST['file'];
    if(!is_file($path)){
      return self::error('File is not available.');
    }$data=@file_get_contents($path);
    if(md5($data)==md5($_POST['content'])){
      return self::error('Content has no changed.');
    }$put=@file_put_contents($path,$_POST['content']);
    if(!$put){
      return self::error('Failed to save file.');
    }return self::result();
  }
  private static function fileContent(){
    if(!isset($_POST['namespace'],$_POST['file'])
      ||!preg_match('/^[a-z0-9]+$/',$_POST['namespace'])
      ||preg_match('/^\./',$_POST['file'])){
      return self::error('Invalid data request.');
    }$apps=unserialize(EDAY_APPS);
    if(!array_key_exists($_POST['namespace'],$apps)){
      return self::error('Application is not available.');
    }$path=EDAY_APP_DIR.$_POST['namespace'].'/'.$_POST['file'];
    if(!is_file($path)){
      return self::error('File is not available.');
    }$data=@file_get_contents($path);
    if($data===false){
      return self::error('Failed to get file content.');
    }return self::result($data==''?' ':$data);
  }
  private static function saveAppConfig(){
    if(!isset($_POST['namespace'],$_POST['data'])||!preg_match('/^[a-z0-9]+$/',$_POST['namespace'])){
      return self::error('Invalid data request.');
    }$apps=unserialize(EDAY_APPS);
    if(!array_key_exists($_POST['namespace'],$apps)){
      return self::error('Application is not available.');
    }$data=@json_decode($_POST['data'],true);
    if(!is_array($data)){
      return self::error('Failed to parse data configuration.');
    }$ns=$_POST['namespace'];
    $path=EDAY_APP_DIR.$ns.'/'.$apps[$ns]->config;
    $temp=['; generated by e-Day at '.date('Y-m-d H:i:s')];
    foreach($data as $type=>$inner){
      $temp[]="\r\n".'['.$type.']';
      foreach($inner as $key=>$value){
        $value=trim($value);
        if(!empty($value)&&!preg_match('/^\d+$/',$value)){
          $value='"'.preg_replace('/"/','\\"',$value).'"';
        }$temp[]=$key.'='.$value;
      }
    }$content=implode("\r\n",$temp)."\r\n\r\n\r\n";
    $put=@file_put_contents($path,$content);
    if(!$put){
      return self::error('Failed to save configuration.');
    }return self::result();
  }
  private static function activateApp(){
    if(!isset($_POST['namespace'])||!preg_match('/^[a-z0-9]+$/',$_POST['namespace'])){
      return self::error('Invalid namespace.');
    }
    $apps=unserialize(EDAY_APPS);
    if(!array_key_exists($_POST['namespace'],$apps)){
      return self::error('Application is not available.');
    }
    self::saveConfigINI($_POST['namespace']);
    $db=site::db();
    $upd=$db->query('update site '.http_build_query([
      'app'=>'string('.$_POST['namespace'].')'
    ]).' where id=1');
    if(!$upd||$db->error){
      return self::error($db->error?$db->error:'Failed to activate the application.');
    }return self::result();
  }
  private static function saveConfigINI(string $appNS){
    $file=EDAY_ROOT.'config.ini';
    $tfile=EDAY_ROOT.'config.ini.tmp';
    if(!is_file($file)||!is_readable($file)){
      return false;
    }@copy($file,$tfile);
    $old=@file($file,FILE_IGNORE_NEW_LINES);
    if(!is_array($old)){return false;}
    $current='app="'.site::config('app').'"';
    $key=array_search($current,$old);
    if(!in_array($current,$old)
      ||!isset($old[$key])){
      return false;
    }$old[$key]='app="'.$appNS.'"';
    $put=@file_put_contents($file,implode("\r\n",$old));
    if(!$put){@copy($tfile,$file);}
    @unlink($tfile);
    return true;
  }
  private static function files($ns=null){
    if(!is_string($ns)){return false;}
    $t=@unserialize(EDAY_APPS);
    $dir=EDAY_APP_DIR.$ns.'/';
    if(!$t||!isset($t[$ns])||!is_dir($dir)){return false;}
    return self::explore($dir);
  }
  private static function explore($d=null){
    $s=@array_diff(@scandir($d),['.','..']);
    $s=is_array($s)?$s:[];$r=[];
    foreach($s as $f){
      if(is_file($d.$f)){
        if(preg_match(self::excludePattern(),$f)){
          continue;
        }$r[]=$d.$f;
      }elseif(is_dir($d.$f)){
        $n=self::explore($d.$f.'/');
        $r=array_merge($r,$n);
      }
    }return $r;
  }
  private static function excludePattern(){
    $r=[
      'ttf','woff','woff2','eot',
      'jpg','jpeg','png','gif','ico',
    ];return '/\.('.implode('|',$r).')$/i';
  }
  private static function configData($ns=null){
    if(!is_string($ns)){return false;}
    $a=(object)@unserialize(EDAY_APPS);
    $path=EDAY_APP_DIR.$ns.'/'.$a->$ns->config;
    if(!is_file($path)){return false;}
    $ini=@parse_ini_file($path,true);
    if(!is_array($ini)){return false;}
    return $ini;
  }
  private static function error($s=null){
    $s=is_string($s)?$s:'Unknown error.';
    return self::result('Error: '.$s);
  }
  private static function result($s=null){
    $s=is_string($s)?$s:'OK';
    header('Content-Type: text/plain');
    header('Content-Length: '.strlen($s));
    header('HTTP/1.1 200 OK');
    exit($s);
  }
}
